//
// Created by deril on 2/26/26.
//

#pragma once

#include "VoxCore/Define.h"

RENDER_NS
enum PassTransition {
    NONE_W_ATTACHMENT,
    NONE_W_COPY,
    W_ATTACHMENT_W_SHADER,
    R_ATTACHMENT_W_SHADER,
    R_ATTACHMENT_R_SHADER,
    W_ATTACHMENT_W_ATTACHMENT,
    R_ATTACHMENT_W_ATTACHMENT,
    R_ATTACHMENT_R_ATTACHMENT,
    W_ATTACHMENT_R_ATTACHMENT,
    W_ATTACHMENT_W_COPY,
    R_ATTACHMENT_W_COPY,
    R_ATTACHMENT_R_COPY,
    W_ATTACHMENT_R_COPY,
    W_COPY_W_SHADER,
    R_COPY_R_SHADER,
    W_COPY_R_SHADER,
    R_COPY_W_SHADER
};
NS_END
