//
// Created by deril on 3/1/26.
//

#pragma once

#include <vulkan/vulkan_core.h>
#include "VoxCore/Define.h"
#include "VoxEngine/render/Enums.h"

RENDER_NS
    DEFINE_ENUM_CONVERTER_VK(Format, VkFormat, FORMAT_LIST);
    DEFINE_ENUM_CONVERTER_FROM_VK(Format, VkFormat, FORMAT_LIST);

    DEFINE_ENUM_CONVERTER_VK(ShaderStage, VkShaderStageFlagBits, SHADER_STAGE_LIST);
    DEFINE_ENUM_CONVERTER_FROM_VK(ShaderStage, VkShaderStageFlagBits, SHADER_STAGE_LIST);

    DEFINE_ENUM_CONVERTER_VK(IndexType, VkIndexType, INDEX_TYPE_LIST);
    DEFINE_ENUM_CONVERTER_FROM_VK(IndexType, VkIndexType, INDEX_TYPE_LIST);

    DEFINE_ENUM_CONVERTER_VK(BufferUsage, VkBufferUsageFlagBits, BUFFER_USAGE_LIST);
    DEFINE_ENUM_CONVERTER_FROM_VK(BufferUsage, VkBufferUsageFlagBits, BUFFER_USAGE_LIST);

    DEFINE_ENUM_CONVERTER_VK(PrimitiveTopology, VkPrimitiveTopology, PRIMITIVE_TOPOLOGY_LIST);
    DEFINE_ENUM_CONVERTER_FROM_VK(PrimitiveTopology, VkPrimitiveTopology, PRIMITIVE_TOPOLOGY_LIST);

    DEFINE_ENUM_CONVERTER_VK(PolygonMode, VkPolygonMode, POLYGON_MODE_LIST);
    DEFINE_ENUM_CONVERTER_FROM_VK(PolygonMode, VkPolygonMode, POLYGON_MODE_LIST);

    DEFINE_ENUM_CONVERTER_VK(CullMode, VkCullModeFlagBits, CULL_MODE_LIST);
    DEFINE_ENUM_CONVERTER_FROM_VK(CullMode, VkCullModeFlagBits, CULL_MODE_LIST);

    DEFINE_ENUM_CONVERTER_VK(FrontFace, VkFrontFace, FRONT_FACE_LIST);
    DEFINE_ENUM_CONVERTER_FROM_VK(FrontFace, VkFrontFace, FRONT_FACE_LIST);

    DEFINE_ENUM_CONVERTER_VK(BlendFactor, VkBlendFactor, BLEND_FACTOR_LIST);
    DEFINE_ENUM_CONVERTER_FROM_VK(BlendFactor, VkBlendFactor, BLEND_FACTOR_LIST);

    DEFINE_ENUM_CONVERTER_VK(BlendOp, VkBlendOp, BLEND_OP_LIST);
    DEFINE_ENUM_CONVERTER_FROM_VK(BlendOp, VkBlendOp, BLEND_OP_LIST);


    DEFINE_ENUM_CONVERTER_VK(MSAASamples, VkSampleCountFlagBits, MSAA_COUNT_LIST);
    DEFINE_ENUM_CONVERTER_FROM_VK(MSAASamples, VkSampleCountFlagBits, MSAA_COUNT_LIST);
NS_END
